// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(myDbContext))]
    partial class myDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DeliveryMangementSystem.Models.Account", b =>
                {
                    b.Property<string>("Account_ID")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Shipper_Id")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Account_ID");

                    b.HasIndex("Shipper_Id")
                        .IsUnique()
                        .HasFilter("[Shipper_Id] IS NOT NULL");

                    b.ToTable("ACCOUNT");
                });

            modelBuilder.Entity("DeliveryMangementSystem.Models.Branch", b =>
                {
                    b.Property<string>("Branch_ID")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Branch_ID");

                    b.ToTable("BRANCH");
                });

            modelBuilder.Entity("DeliveryMangementSystem.Models.Customer", b =>
                {
                    b.Property<string>("Customer_ID")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.HasKey("Customer_ID");

                    b.ToTable("CUSTOMER");
                });

            modelBuilder.Entity("DeliveryMangementSystem.Models.Order", b =>
                {
                    b.Property<string>("Order_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Branch_ID")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("Customer_ID")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<DateTime?>("Delivery_Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Order_Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Payment_Method")
                        .HasColumnType("int");

                    b.Property<string>("Shipper_ID")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Total_Amount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Order_ID");

                    b.HasIndex("Branch_ID");

                    b.HasIndex("Customer_ID");

                    b.HasIndex("Shipper_ID");

                    b.ToTable("xORDER");
                });

            modelBuilder.Entity("DeliveryMangementSystem.Models.Shipper", b =>
                {
                    b.Property<string>("Shipper_ID")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.HasKey("Shipper_ID");

                    b.ToTable("SHIPPER");
                });

            modelBuilder.Entity("DeliveryMangementSystem.Models.Account", b =>
                {
                    b.HasOne("DeliveryMangementSystem.Models.Shipper", "Shipper")
                        .WithOne("Account")
                        .HasForeignKey("DeliveryMangementSystem.Models.Account", "Shipper_Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DeliveryMangementSystem.Models.Order", b =>
                {
                    b.HasOne("DeliveryMangementSystem.Models.Branch", "Branch")
                        .WithMany("Orders")
                        .HasForeignKey("Branch_ID");

                    b.HasOne("DeliveryMangementSystem.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("Customer_ID");

                    b.HasOne("DeliveryMangementSystem.Models.Shipper", "Shipper")
                        .WithMany("Orders")
                        .HasForeignKey("Shipper_ID");
                });
#pragma warning restore 612, 618
        }
    }
}
