// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DeliveryMangementSystem.Migrations
{
    [DbContext(typeof(myDbContext))]
    [Migration("20250405061651_v2_0_1")]
    partial class v2_0_1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DeliveryMangementSystem.Models.ACCOUNT", b =>
                {
                    b.Property<string>("Account_ID")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("S_ID")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Account_ID");

                    b.HasIndex("S_ID")
                        .IsUnique()
                        .HasFilter("[S_ID] IS NOT NULL");

                    b.ToTable("ACCOUNT");
                });

            modelBuilder.Entity("DeliveryMangementSystem.Models.BRANCH", b =>
                {
                    b.Property<string>("Branch_ID")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Branch_ID");

                    b.ToTable("BRANCH");
                });

            modelBuilder.Entity("DeliveryMangementSystem.Models.CUSTOMER", b =>
                {
                    b.Property<string>("Customer_ID")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.HasKey("Customer_ID");

                    b.ToTable("CUSTOMER");
                });

            modelBuilder.Entity("DeliveryMangementSystem.Models.ORDER", b =>
                {
                    b.Property<string>("Order_ID")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("Branch_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("Customer_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<DateTime?>("Delivery_Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Payment_Method")
                        .HasColumnType("int");

                    b.Property<string>("Shipper_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Total_Amount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Order_ID");

                    b.HasIndex("Branch_ID");

                    b.HasIndex("Customer_ID");

                    b.HasIndex("Shipper_ID");

                    b.ToTable("xORDER");
                });

            modelBuilder.Entity("DeliveryMangementSystem.Models.SHIPPER", b =>
                {
                    b.Property<string>("Shipper_ID")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.HasKey("Shipper_ID");

                    b.ToTable("SHIPPER");
                });

            modelBuilder.Entity("DeliveryMangementSystem.Models.ACCOUNT", b =>
                {
                    b.HasOne("DeliveryMangementSystem.Models.SHIPPER", "Shipper")
                        .WithOne("Account")
                        .HasForeignKey("DeliveryMangementSystem.Models.ACCOUNT", "S_ID")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("DeliveryMangementSystem.Models.ORDER", b =>
                {
                    b.HasOne("DeliveryMangementSystem.Models.BRANCH", "Branch")
                        .WithMany("Orders")
                        .HasForeignKey("Branch_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeliveryMangementSystem.Models.CUSTOMER", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("Customer_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeliveryMangementSystem.Models.SHIPPER", "Shipper")
                        .WithMany("Orders")
                        .HasForeignKey("Shipper_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
